src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $firstname;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 10,
     *      max = 10,
     *      minMessage = "la longueur minimum ne doit pas dépasser {{ limit }} chiffres ",
     *      maxMessage = "la longueur maximum ne doit pas dépasser {{ limit }} chiffres"
     * )
     */
    private $phoneNumber;

    /**
     * @ORM\OneToOne(targetEntity=Localisation::class, cascade={"persist", "remove"})
     */
    private $Localisation;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\OneToMany(targetEntity=Restaurant::class, mappedBy="user")
     */
    private $restaurants;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFilename;

    /**
     * @ORM\Column(type="integer", nullable=true, options={"default": "250"})
     */
    private $sold;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }


    public function __construct()
    {
        $this->restaurants = new ArrayCollection();
    }



    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(int $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }


    public function getLocalisation(): ?Localisation
    {
        return $this->Localisation;
    }

    public function setLocalisation(?Localisation $Localisation): self
    {
        $this->Localisation = $Localisation;

        return $this;
    }

    /**
     * A visual identifier that represents this User.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every User at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the User, clear it here
        // $this->plainPassword = null;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    /**
     * @return Collection|Restaurant[]
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }

    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant)) {
            $this->restaurants[] = $restaurant;
            $restaurant->setUser($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): self
    {
        if ($this->restaurants->removeElement($restaurant)) {
            // set the owning side to null (unless already changed)
            if ($restaurant->getUser() === $this) {
                $restaurant->setUser(null);
            }
        }

        return $this;
    }

    public function getImageFilename(): ?string
    {
        return $this->imageFilename;
    }

    public function setImageFilename(?string $imageFilename): self
    {
        $this->imageFilename = $imageFilename;

        return $this;
    }

    public function getSold(): ?int
    {
        return $this->sold;
    }

    public function setSold(?int $sold): self
    {
        $this->sold = $sold;

        return $this;
    }


}

templates/index/card.html.twig
<div class="card mx-4 my-4" style="width: 20em">
    {% if not plat.imageFilename is empty %}
        <img class="card-img-top" src="{{ asset('uploads/plats_logo/' ~ plat.imageFilename) | imagine_filter('thumb')}}" alt="Image du plat">
    {% endif %}
    {% if plat.imageFilename is empty %}
        <img class="card-img-top" src="{{ asset('noimg/image.jpg') | imagine_filter('thumb')}}" alt="Card image cap">
    {% endif %}
      <div class="card-body">
        <h5 class="card-title">Nom : {{ plat.name }}</h5>
        <h6 class="card-text">Prix : {{ plat.price }}€</h6>
        <p class="card-text"><small class="text-muted"></small></p>
        <a href="{{ path('panier_add', {'id': plat.id}) }}" class="btn btn-primary">Ajouter au panier</a>
  </div>
</div>

templates/index/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil | QuickEat{% endblock %}

{% block body %}
    <section>
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://getintheloop.ca/wp-content/uploads/2020/10/Steinbach-Header.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://www.laplancha-angouleme.fr/userfiles/7370/bandeau-07.jpg" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://magasins.pizzabonici.com/media/magiccart/magicslider/cache/1920x800//p/i/pizza_background.jpg" class="d-block w-100" alt="..." >
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div>
    </section>
    <section class="search-sec">
        <div class="container">
            <form action="#" method="post" novalidate="novalidate">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            {{ form_start(form) }}
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                {{ form_row(form.city) }}
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                {{ form_row(form.name) }}
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                {{ form_row(form.categories) }}
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-12 p-0">
                                <button type="submit" class="btn btn-danger wrn-btn">Rechercher</button>
                            </div>
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <div class="container">
    <div class="d-flex justify-content-center shadow p-3 mb-5 bg-warning rounded">
        <h1>Nos restaurants</h1>
    </div>
    </div>
<div class="container my-5 d-flex flex-wrap justify-content-center">
{% for restaurant in restaurants %}
    <div class="card mx-3 my-3" style="width: 20rem;">
        {% if not restaurant.imageFilename is empty %}
            <img class="card-img-top" src="{{ asset('uploads/resto_logo/' ~ restaurant.imageFilename) | imagine_filter('thumb')}}" alt="Image restaurant">
        {% endif %}
        {% if restaurant.imageFilename is empty %}
            <img class="card-img-top" src="{{ asset('noimg/image.jpg') | imagine_filter('thumb')}}" alt="Card image cap">
        {% endif %}
    <div class="card-body">
        <h5 class="card-title"> Restaurant : {{ restaurant.name }}</h5>
        <p class="card-text">Catégorie : {{ restaurant.categories }}</p>
        <p class="card-text">Ville : {{ restaurant.localisation.city }}</p>
        <a href="{{ path('lerestaurant', {'id': restaurant.id}) }}" class="btn btn-primary">En savoir +</a>
    </div>
    </div>
{% endfor %}
</div>

{% endblock %}

templates/index/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier | QuickEat{% endblock %}

{% block body %}

<div class="container pt-5">
{% if items | length > 0 %}
    <div class="bg-light p-3">
        <h1>Votre panier</h1>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Produits</th>
                <th>Prix</th>
                <th>Quantité</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.plat.name }}</td>
                    <td>{{ item.plat.price }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.plat.price * item.quantity }}</td>
                    <td>
                        <a href="{{ path('panier_remove', {'id': item.plat.id }) }}" class="btn btn-danger btn-sm"><i class="fas fa-trash"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr></tr>
            <tr>
                <td colspan="3" class="text-right">Frais de livraison : </td>
                <td>{{ livraison }}</td>
            </tr>
             <tr>
                <td colspan="3" class="text-right">Total : </td>
                <td>{{ total }}</td>
            </tr>
            <tr>
                <td colspan="4" class="text-right"><button class="btn btn-primary">Commander</button></td>
            </tr>
        </tfoot>
    </table>
{% else %}
<div class="bg-light p-3 my-5">
    <h1>Votre panier est vide</h1>
    <a href="{{ path('index') }}" class="btn btn-primary btn-sm mt-3">Retour à l'Accueil</a>
</div>
{% endif %}
</div>

{% endblock %}

templates/index/restaurant.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{restaurant.name}} | QuickEat{% endblock %}

{% block body %}

<section>
        <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://www.service-quotidien.fr/wp-content/uploads/2019/09/Produits-de-saison-3.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://www.service-quotidien.fr/wp-content/uploads/2019/09/Produits-de-saison-2-3.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://www.service-quotidien.fr/wp-content/uploads/2019/09/Repas-a-la-carte-3.png" class="d-block w-100" alt="..." >
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Précédent</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Suivant</span>
            </a>
        </div>
    </section>

    <div class="d-flex justify-content-center shadow p-3 bg-warning rounded">
        <h1>Bienvenue chez {{restaurant.name}}</h1>
    </div>
<div class="container my-5 d-flex flex-wrap justify-content-center">
{% if (entrees != []) %}
<div class="container">
    <div class="d-flex justify-content-center shadow-sm p-2 my-5 bg-warning rounded">
        <h2>Nos entrées</h2>
    </div>
</div>
<div class="my-4 mx-5 d-flex flex-wrap justify-content-center">
{% for plat in entrees %}
  {{ include('index/card.html.twig', { plat: plat }) }}
{% endfor %}
</div>
{% endif %}


{% if (plats != []) %}
<div class="container">
    <div class="d-flex justify-content-center shadow-sm p-2 my-5 bg-warning rounded">
        <h2>Nos plats</h2>
    </div>
</div>
<div class="my-4 mx-5 d-flex flex-wrap justify-content-center">
{% for plat in plats %}
  {{ include('index/card.html.twig', { plat: plat }) }}
{% endfor %}
</div>
{% endif %}

{% if (desserts != []) %}
<div class="container">
    <div class="d-flex justify-content-center shadow-sm p-2 my-5 bg-warning rounded">
        <h2>Nos desserts</h2>
    </div>
</div>
<div class="my-4 mx-5 d-flex flex-wrap justify-content-center">
{% for plat in desserts %}
  {{ include('index/card.html.twig', { plat: plat }) }}
{% endfor %}
</div>
{% endif %}


{% if (boissons != []) %}
<div class="container">
    <div class="d-flex justify-content-center shadow-sm p-2 my-5 bg-warning rounded">
        <h2>Nos boissons</h2>
    </div>
</div>
<div class="my-4 mx-5 d-flex flex-wrap justify-content-center">
{% for plat in boissons %}
  {{ include('index/card.html.twig', { plat: plat }) }}
{% endfor %}
</div>
{% endif %}
</div>

{% endblock %}